import type { Topic } from '@/types/topic'

export const topics: Topic[] = [
  {
    order: 1,
    slug: 'how-the-web-works',
    title: 'How the Web Works',
    cluster: 'web-foundations',
    difficulty: 'easy',
    interviewFrequency: 'low',
    path: ['fundamentals-first'],
    hldWeight: 'primary',
    status: 'mvp',
    prerequisites: [],
  },
  {
    order: 2,
    slug: 'apis-and-rest',
    title: 'APIs & REST',
    cluster: 'web-foundations',
    difficulty: 'easy',
    interviewFrequency: 'medium',
    path: ['fundamentals-first', 'interview-critical'],
    hldWeight: 'primary',
    status: 'mvp',
    prerequisites: ['how-the-web-works'],
  },
  {
    order: 3,
    slug: 'cdn',
    title: 'Content Delivery Networks (CDN)',
    cluster: 'web-foundations',
    difficulty: 'medium',
    interviewFrequency: 'high',
    path: ['fundamentals-first', 'interview-critical', 'complexity-ladder'],
    hldWeight: 'primary',
    status: 'mvp',
    prerequisites: ['how-the-web-works', 'apis-and-rest'],
  },
  {
    order: 4,
    slug: 'databases-101',
    title: 'Databases 101',
    cluster: 'storage',
    difficulty: 'easy',
    interviewFrequency: 'high',
    path: ['fundamentals-first', 'interview-critical', 'complexity-ladder'],
    hldWeight: 'primary',
    status: 'mvp',
    prerequisites: ['apis-and-rest'],
  },
  {
    order: 5,
    slug: 'database-indexing',
    title: 'Database Indexing',
    cluster: 'storage',
    difficulty: 'medium',
    interviewFrequency: 'high',
    path: ['fundamentals-first', 'interview-critical', 'complexity-ladder'],
    hldWeight: 'supporting',
    status: 'mvp',
    prerequisites: ['databases-101'],
  },
  {
    order: 6,
    slug: 'replication-strategies',
    title: 'Replication Strategies',
    cluster: 'storage',
    difficulty: 'medium',
    interviewFrequency: 'high',
    path: ['fundamentals-first', 'interview-critical', 'complexity-ladder'],
    hldWeight: 'primary',
    status: 'mvp',
    prerequisites: ['databases-101'],
  },
  {
    order: 7,
    slug: 'cap-theorem',
    title: 'CAP Theorem',
    cluster: 'storage',
    difficulty: 'medium',
    interviewFrequency: 'high',
    path: ['fundamentals-first', 'interview-critical', 'complexity-ladder'],
    hldWeight: 'primary',
    status: 'mvp',
    prerequisites: ['databases-101', 'replication-strategies'],
  },
  {
    order: 8,
    slug: 'database-sharding',
    title: 'Database Sharding',
    cluster: 'storage',
    difficulty: 'hard',
    interviewFrequency: 'high',
    path: ['fundamentals-first', 'interview-critical', 'complexity-ladder'],
    hldWeight: 'primary',
    status: 'mvp',
    prerequisites: ['database-indexing', 'cap-theorem', 'scalability'],
  },
  {
    order: 9,
    slug: 'scalability',
    title: 'Scalability',
    cluster: 'scale',
    difficulty: 'easy',
    interviewFrequency: 'high',
    path: ['fundamentals-first', 'interview-critical', 'complexity-ladder'],
    hldWeight: 'primary',
    status: 'mvp',
    prerequisites: ['databases-101', 'apis-and-rest'],
  },
  {
    order: 10,
    slug: 'load-balancing',
    title: 'Load Balancing',
    cluster: 'scale',
    difficulty: 'medium',
    interviewFrequency: 'high',
    path: ['fundamentals-first', 'interview-critical', 'complexity-ladder'],
    hldWeight: 'primary',
    status: 'mvp',
    prerequisites: ['scalability'],
  },
  {
    order: 11,
    slug: 'caching',
    title: 'Caching',
    cluster: 'scale',
    difficulty: 'medium',
    interviewFrequency: 'high',
    path: ['fundamentals-first', 'interview-critical', 'complexity-ladder'],
    hldWeight: 'primary',
    status: 'mvp',
    prerequisites: ['scalability', 'databases-101'],
  },
  {
    order: 12,
    slug: 'message-queues',
    title: 'Message Queues',
    cluster: 'reliability',
    difficulty: 'medium',
    interviewFrequency: 'high',
    path: ['fundamentals-first', 'interview-critical', 'complexity-ladder'],
    hldWeight: 'primary',
    status: 'mvp',
    prerequisites: ['scalability', 'databases-101'],
  },
  {
    order: 13,
    slug: 'rate-limiting-api-gateways',
    title: 'Rate Limiting & API Gateways',
    cluster: 'reliability',
    difficulty: 'medium',
    interviewFrequency: 'high',
    path: ['fundamentals-first', 'interview-critical', 'complexity-ladder'],
    hldWeight: 'primary',
    status: 'mvp',
    prerequisites: ['apis-and-rest', 'load-balancing'],
  },
  {
    order: 14,
    slug: 'resilience-patterns',
    title: 'Resilience Patterns',
    cluster: 'reliability',
    difficulty: 'medium',
    interviewFrequency: 'high',
    path: ['fundamentals-first', 'interview-critical', 'complexity-ladder'],
    hldWeight: 'primary',
    status: 'mvp',
    prerequisites: ['message-queues', 'load-balancing', 'caching'],
  },
]

export function getTopicBySlug(slug: string): Topic | undefined {
  return topics.find((t) => t.slug === slug)
}

export function getTopicsByPath(path: Topic['path'][number]): Topic[] {
  return topics
    .filter((t) => t.path.includes(path) && t.status === 'mvp')
    .sort((a, b) => a.order - b.order)
}
